version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: ai-hukum-backend
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL:-claude-3-haiku-20240307}
      - CORS_ORIGINS=*
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE: http://localhost:8000
    container_name: ai-hukum-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

